# Generated by Django 5.2.12 on 2026-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('t1', 'BOM & 2D Drawing'), ('t2', 'Layout Designer')], max_length=10, null=True),
        ),
    ]
