# Generated by Django 5.2.12 on 2026-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
