# Generated by Django 5.2.12 on 2026-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
