# Generated by Django 5.2.12 on 2026-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
