steps:
  # Step 1: Checkout the code from GitHub
  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['clone', 'https://github.com/Misbahhassan08/solar_server']
  
  # Step 2: Change directory to the repository
  - name: 'gcr.io/cloud-builders/docker'
    # dir: 'solar_server'
    args: ['build', '-t', 'gcr.io/vertex-model-training/solar_server', '.']

 
  
  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    # dir: 'solar_server'
    args: ['push', 'gcr.io/vertex-model-training/solar_server']
  
  # Step 4: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'solar-server'
      - '--image'
      - 'gcr.io/vertex-model-training/solar_server'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--set-secrets'
      - 'CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest,CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest,CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest'

timeout: '1200s'  # Adjust timeout as necessary
options:
  logging: CLOUD_LOGGING_ONLY
