# Generated by Django 5.2.12 on 2026-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
