# Generated by Django 5.2.12 on 2026-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_duration_days_alter_userplan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='projects_limit',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='projects_used',
        ),
        migrations.AddField(
            model_name='plan',
            name='t1_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='t2_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='t1_projects_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='t2_projects_used',
            field=models.IntegerField(default=0),
        ),
    ]
