# Generated by Django 5.2.12 on 2026-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_projects_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='t1_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='t2_limit',
        ),
        migrations.AddField(
            model_name='plan',
            name='projects_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
