# Generated by Django 5.2.12 on 2026-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_t1_limit_remove_plan_t2_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name', 'tool']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='projects_limit',
        ),
        migrations.AddField(
            model_name='plan',
            name='t1_projects_limit',
            field=models.IntegerField(blank=True, help_text='Leave empty if not applicable', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='t2_projects_limit',
            field=models.IntegerField(blank=True, help_text='Leave empty if not applicable', null=True),
        ),
    ]
