# Generated by Django 5.2.12 on 2026-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_plan_options_remove_plan_projects_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Invoice price for this plan', max_digits=10),
        ),
    ]
