# Generated by Django 5.2.12 on 2026-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.TextField(blank=True, help_text='Enter features separated by commas'),
        ),
    ]
