# Generated by Django 5.2.12 on 2026-04-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['tool', 'price']},
        ),
    ]
