# Generated by Django 5.2.11 on 2026-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short SEO description / excerpt.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image_alt",
            field=models.CharField(
                blank=True, help_text="Alt text for the blog image.", max_length=255
            ),
        ),
    ]
