# Generated by Django 5.2.12 on 2026-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_created_at_customer_demo_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
