# Generated by Django 5.2.12 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
