# Generated by Django 5.2.12 on 2026-04-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_active_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active_token',
        ),
    ]
