# Generated by Django 5.2.12 on 2026-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='token',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
