# Generated by Django 5.2.12 on 2026-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usersession_token_usersession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active_account',
            field=models.BooleanField(default=True),
        ),
    ]
